[project]
name = "propms"
authors = [
    { name = "Aakvatech", email = "info@aakvatech.com" }
]
description = "Property Management Solution"
requires-python = ">=3.10"
readme = "README.md"
dynamic = ["version"]
dependencies = []

[project.optional-dependencies]
dev = [
    "pre-commit",
]

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[tool.bench.frappe-dependencies]
frappe = ">=15.0.0,<16.0.0"
erpnext = ">=15.0.0,<16.0.0"

[tool.ruff]
line-length = 110
target-version = "py310"

[tool.ruff.format]
quote-style = "double"
indent-style = "tab"
docstring-code-format = true

[tool.ruff.lint]
select = ["F", "E", "W", "I", "UP", "B"]
ignore = ["E101", "E402", "E501", "E741", "W191"]

# These dependencies are only installed when developer mode is enabled
[tool.bench.dev-dependencies]
# package_name = "~=1.1.0"

[tool.setuptools.dynamic]
version = {attr = "propms.__version__"}
